const API = '/api';
const state = { token: localStorage.getItem('hotel_token') || '', user: JSON.parse(localStorage.getItem('hotel_user') || 'null'), hotels: [], roomTypes: [], rooms: [] };
const $ = id => document.getElementById(id);
const esc = v => String(v ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function toast(message, error=false){const el=$('toast');el.textContent=message;el.className='toast show'+(error?' error':'');setTimeout(()=>el.className='toast',3000)}
async function api(path, options={}){const headers={'Content-Type':'application/json',...(options.headers||{})};if(state.token)headers.Authorization=`Bearer ${state.token}`;const res=await fetch(API+path,{...options,headers});let data={};try{data=await res.json()}catch{}if(!res.ok)throw new Error(data.message||data.error||'Request failed');return data}
function authState(){localStorage.setItem('hotel_token',state.token);localStorage.setItem('hotel_user',JSON.stringify(state.user));renderAuth();}
function renderAuth(){const nav=$('mainNav'), area=$('authArea');nav.innerHTML='<a href="#search">Search</a><a href="#about">Modules</a>'+(state.user?'<a href="#dashboard">Dashboard</a>':'');area.innerHTML=state.user?`<span>${esc(state.user.name)} · ${esc(state.user.role)}</span><button class="btn small ghost" id="logoutBtn">Logout</button>`:'<button class="btn small primary" data-go="auth">Login</button>';if($('logoutBtn'))$('logoutBtn').onclick=()=>{state.token='';state.user=null;authState();$('dashboard').classList.add('hidden');$('admin').classList.add('hidden');toast('Logged out')};document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.go)?.scrollIntoView({behavior:'smooth'}));}
async function loadHotels(){try{const d=await api('/hotels');state.hotels=d.data||[];const opts=state.hotels.length?state.hotels.map(h=>`<option value="${h._id}">${esc(h.name)} — ${esc(h.city)}</option>`).join(''):'<option value="">No hotels yet — ask admin to create one</option>';['searchHotel','roomTypeHotel','roomHotel'].forEach(id=>{if($(id))$(id).innerHTML=opts});}catch(e){toast(e.message,true)}}
async function loadRoomTypes(){try{const d=await api('/room-types');state.roomTypes=d.data||[];if($('roomType'))$('roomType').innerHTML='<option value="">Select room type</option>'+state.roomTypes.map(r=>`<option value="${r._id}">${esc(r.name)} · ₹${Number(r.basePrice).toLocaleString()}</option>`).join('')}catch(e){toast(e.message,true)}}
async function loadRooms(){try{const d=await api('/rooms');state.rooms=d.data||[];renderRooms()}catch(e){toast(e.message,true)}}
function renderRooms(){if(!$('roomList'))return;if(!state.rooms.length){$('roomList').innerHTML='<p class="muted">No rooms created yet.</p>';return}$('roomList').innerHTML='<table class="room-table"><thead><tr><th>Room</th><th>Hotel</th><th>Type</th><th>Status</th><th>Housekeeping</th></tr></thead><tbody>'+state.rooms.map(r=>`<tr><td>${esc(r.roomNumber)}</td><td>${esc(r.hotelId?.name||'—')}</td><td>${esc(r.roomTypeId?.name||'—')}</td><td>${esc(r.status)}</td><td>${esc(r.housekeepingStatus||'—')}</td></tr>`).join('')+'</tbody></table>'}
function renderModules(){const items=['Guest Registration & Authentication','Hotel & Property Management','Room Type & Inventory Management','Availability Search Engine','Reservation Booking Workflow','Dynamic Pricing Rules','Booking Status Management','Check-in / Check-out','Housekeeping Status Tracking','Cancellation & Refund Policy','Guest Booking History','Invoice Generation Summary','Admin Occupancy Reports'];$('moduleGrid').innerHTML=items.map((x,i)=>`<article class="module"><div class="module-num">0${i+1}</div><h3>${x}</h3><p>Implemented through the REST API and represented in the demo workspace.</p></article>`).join('')}
function showAuthTab(tab){document.querySelectorAll('[data-auth-tab]').forEach(b=>b.classList.toggle('active',b.dataset.authTab===tab));$('loginForm').classList.toggle('hidden',tab!=='login');$('registerForm').classList.toggle('hidden',tab!=='register')}
async function login(e){e.preventDefault();try{const d=await api('/auth/login',{method:'POST',body:JSON.stringify({email:$('loginEmail').value,password:$('loginPassword').value})});state.token=d.token;state.user=d.user;authState();$('dashboard').classList.remove('hidden');if(state.user.role==='Admin')$('admin').classList.remove('hidden');toast('Login successful');await refreshDashboard();document.getElementById('dashboard').scrollIntoView({behavior:'smooth'})}catch(err){toast(err.message,true)}}
async function register(e){e.preventDefault();try{await api('/auth/register',{method:'POST',body:JSON.stringify({name:$('registerName').value,email:$('registerEmail').value,password:$('registerPassword').value})});toast('Account created. Please login.');showAuthTab('login');$('loginEmail').value=$('registerEmail').value}catch(err){toast(err.message,true)}}
async function searchAvailability(e){e.preventDefault();const hotelId=$('searchHotel').value;const ci=$('checkIn').value,co=$('checkOut').value;if(!hotelId)return toast('Create a hotel first',true);try{const d=await api(`/hotels/search?hotelId=${encodeURIComponent(hotelId)}&checkIn=${encodeURIComponent(ci)}&checkOut=${encodeURIComponent(co)}`);const rooms=d.data||[];$('searchResults').innerHTML=rooms.length?rooms.map(r=>`<article class="room-card"><span class="eyebrow">ROOM ${esc(r.roomNumber)}</span><h3>${esc(r.roomTypeId?.name||'Room')}</h3><div class="room-meta"><span class="chip">Capacity ${esc(r.roomTypeId?.capacity||'—')}</span><span class="chip">${esc(r.status)}</span></div><div class="price">₹${Number(r.roomTypeId?.basePrice||0).toLocaleString()} <small>/ night</small></div><button class="btn primary full" data-book-room="${r._id}" data-hotel="${r.hotelId?._id||hotelId}">Book this room</button></article>`).join(''):'<div class="panel"><h3>No available rooms</h3><p>Try another date range or ask the admin to add inventory.</p></div>';document.querySelectorAll('[data-book-room]').forEach(b=>b.onclick=()=>bookRoom(b.dataset.bookRoom,ci,co))}catch(err){toast(err.message,true)}}
async function bookRoom(roomId,ci,co){if(!state.token){toast('Please login as a guest before booking',true);document.getElementById('auth').scrollIntoView({behavior:'smooth'});return}try{const d=await api('/bookings',{method:'POST',body:JSON.stringify({roomId,checkIn:ci,checkOut:co,addOns:[]})});toast('Booking created successfully');await refreshDashboard();document.getElementById('dashboard').scrollIntoView({behavior:'smooth'});console.log(d)}catch(err){toast(err.message,true)}}
async function refreshDashboard(){if(!state.user)return;const role=state.user.role;$('welcomeTitle').textContent=`Welcome back, ${state.user.name}`;$('rolePill').textContent=role;$('adminPanel').classList.toggle('hidden',role!=='Admin');$('dashboardStats').innerHTML=[['13','Core modules'],['JWT','Protected auth'],['REST','API workflow'],[role,'Current role']].map(x=>`<div class="stat"><b>${x[0]}</b><span>${x[1]}</span></div>`).join('');try{const d=await api(`/guests/${state.user.id}/bookings`);const list=d.data||d.bookings||[];$('bookingList').innerHTML=list.length?list.map(b=>`<div class="booking-row"><div class="booking-main"><div><strong>Room ${esc(b.roomId?.roomNumber||b.roomId||'—')}</strong><div class="muted">${new Date(b.checkIn).toLocaleDateString()} → ${new Date(b.checkOut).toLocaleDateString()}</div></div><span class="status ${b.status==='CANCELLED'?'cancelled':''}">${esc(b.status)}</span></div><div style="margin-top:8px">₹${Number(b.totalAmount||0).toLocaleString()} · <button class="btn small ghost" data-invoice="${b._id}">Invoice</button> ${['RESERVED','CONFIRMED'].includes(b.status)?`<button class="btn small ghost" data-cancel="${b._id}">Cancel</button>`:''}</div></div>`).join(''):'<p class="muted">No bookings yet. Search for an available room above.</p>';document.querySelectorAll('[data-cancel]').forEach(b=>b.onclick=()=>cancelBooking(b.dataset.cancel));document.querySelectorAll('[data-invoice]').forEach(b=>b.onclick=()=>invoice(b.dataset.invoice))}catch(err){$('bookingList').innerHTML=`<p class="muted">${esc(err.message)}</p>`}if(role==='Admin'){await loadHotels();await loadRoomTypes();await loadRooms()}}
async function cancelBooking(id){try{await api(`/bookings/${id}/cancel`,{method:'PUT',body:JSON.stringify({reason:'Cancelled from frontend'})});toast('Booking cancelled');refreshDashboard()}catch(e){toast(e.message,true)}}
async function invoice(id){try{const d=await api(`/bookings/${id}/invoice`);const i=d.invoice;toast(`Invoice: ₹${Number(i.totalAmount).toLocaleString()} · ${i.numberOfNights} night(s)`);alert(`INVOICE\nBooking: ${i.bookingId}\nNights: ${i.numberOfNights}\nRoom: ₹${i.roomCost}\nDynamic pricing: ₹${i.dynamicPricing}\nAdd-ons: ₹${i.addOns}\nTax: ₹${i.tax}\nTOTAL: ₹${i.totalAmount}`)}catch(e){toast(e.message,true)}}
async function createHotel(e){e.preventDefault();try{await api('/admin/hotels',{method:'POST',body:JSON.stringify({name:$('hotelName').value,city:$('hotelCity').value,amenities:$('hotelAmenities').value.split(',').map(x=>x.trim()).filter(Boolean),rating:Number($('hotelRating').value||0)})});toast('Hotel created');e.target.reset();await loadHotels()}catch(e){toast(e.message,true)}}
async function createRoomType(e){e.preventDefault();try{await api('/admin/room-types',{method:'POST',body:JSON.stringify({hotelId:$('roomTypeHotel').value,name:$('roomTypeName').value,capacity:Number($('roomCapacity').value),basePrice:Number($('roomPrice').value),totalRooms:Number($('roomTotal').value),description:'Created from frontend demo'})});toast('Room type created');e.target.reset();await loadRoomTypes()}catch(e){toast(e.message,true)}}
async function createRoom(e){e.preventDefault();try{await api('/admin/rooms',{method:'POST',body:JSON.stringify({hotelId:$('roomHotel').value,roomTypeId:$('roomType').value,roomNumber:$('roomNumber').value,status:'available'})});toast('Room created');e.target.reset();await loadRooms()}catch(e){toast(e.message,true)}}
async function report(type){try{const d=await api(`/admin/reports/${type}`);const r=d.report;$('reportOutput').innerHTML=type==='occupancy'?`<div class="report-card"><div class="big">${r.occupancyPercentage}%</div><p>Current occupancy</p><div class="mini"><div><b>${r.totalRooms}</b><small> Total rooms</small></div><div><b>${r.occupiedRooms}</b><small> Occupied</small></div><div><b>${r.availableRooms}</b><small> Available</small></div></div></div>`:`<div class="report-card"><div class="big">₹${Number(r.totalRevenue).toLocaleString()}</div><p>Realized revenue</p><div class="mini"><div><b>${r.totalBookings}</b><small> Bookings</small></div><div><b>₹${Number(r.taxes).toLocaleString()}</b><small> Taxes</small></div></div></div>`}catch(e){toast(e.message,true)}}
$('loginForm').addEventListener('submit',login);$('registerForm').addEventListener('submit',register);$('availabilityForm').addEventListener('submit',searchAvailability);document.querySelectorAll('[data-auth-tab]').forEach(b=>b.onclick=()=>showAuthTab(b.dataset.authTab));$('refreshBookings').onclick=refreshDashboard;$('hotelForm').addEventListener('submit',createHotel);$('roomTypeForm').addEventListener('submit',createRoomType);$('roomForm').addEventListener('submit',createRoom);$('occupancyBtn').onclick=()=>report('occupancy');$('revenueBtn').onclick=()=>report('revenue');$('refreshRooms').onclick=loadRooms;renderModules();renderAuth();loadHotels();if(state.user){$('dashboard').classList.remove('hidden');if(state.user.role==='Admin')$('admin').classList.remove('hidden');refreshDashboard()}document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.go)?.scrollIntoView({behavior:'smooth'}));
